<div class="side-buttons">
  <div class="side-buttons-box mobile_code">
    <span class="bt-left"><i class="fa fa-mobile-phone fa-2x" title="手机访问"></i></span><span style="font-size:1px;display:inline-block;line-height:16px;clear:both;">扫二维码</span>
	<div class="code_img"><i></i><img src="{{ theme.mobile_code.qcode }}" alt="{{ theme.mobile_code.description }}"><p>扫一扫，用手机访问本站</p></div>
  </div>
  <div class="side-buttons-box mail_box">
    <a href="mailto:wuxubj@qq.com"><span class="bt-left"><i class="fa fa-envelope-o fa-lg" title="发送邮件"></i></span><span style="font-size:1px;display:inline-block;line-height:16px;clear:both;">发送邮件</span></a>
  </div>
</div>